# generate config files
python "/Users/alex/Documents/Work/UWyo/Research/Flux Pipeline Project/Eddypro-ec-testing/workflows/basic_python/basic_workflow.py"

eddypro_rp="/Users/alex/Documents/Work/UWyo/Research/Flux Pipeline Project/Eddypro-ec-testing/eddypro/eddypro_rp"
eddypro_fcc="/Users/alex/Documents/Work/UWyo/Research/Flux Pipeline Project/Eddypro-ec-testing/eddypro/eddypro_fcc"
environment="/Users/alex/Documents/Work/UWyo/Research/Flux Pipeline Project/Eddypro-ec-testing/workflows/basic_python"
# first eddypro call: generate planar fit data
PROJ_FILE="/Users/alex/Documents/Work/UWyo/Research/Flux Pipeline Project/Eddypro-ec-testing/workflows/basic_python/ini/pf_base.eddypro"
"${eddypro_rp}" \
    -s mac \
    -e "${environment}" \
    "${PROJ_FILE}"
"${eddypro_fcc}" \
    -s mac \
    -e "${environment}" \
    "${PROJ_FILE}"

# subsequent eddypro calls: use planar fit data generated by first call

