
eddypro_rp="/Users/alex/Documents/Work/UWyo/Research/Flux Pipeline Project/Eddypro-ec-testing/eddypro/eddypro_rp"
eddypro_fcc="/Users/alex/Documents/Work/UWyo/Research/Flux Pipeline Project/Eddypro-ec-testing/eddypro/eddypro_fcc"
environment="/Users/alex/Documents/Work/UWyo/Research/Flux Pipeline Project/Eddypro-ec-testing/workflows/basic_python"
script="/Users/alex/Documents/Work/UWyo/Research/Flux Pipeline Project/Eddypro-ec-testing/workflows/basic_python/basic_workflow.py"

# generate config file for manual planar fit mode
python "${script}"
# first eddypro call: generate planar fit data
PROJ_FILE="/Users/alex/Documents/Work/UWyo/Research/Flux Pipeline Project/Eddypro-ec-testing/workflows/basic_python/ini/pf_base.eddypro"
"${eddypro_rp}" \
    -s mac \
    -e "${environment}" \
    "${PROJ_FILE}"
"${eddypro_fcc}" \
    -s mac \
    -e "${environment}" \
    "${PROJ_FILE}"

# subsequent eddypro calls: use planar fit data generated by first call
# generate config files for sensitivity analysis
python "${script}" --pf_file
# first eddypro call: generate planar fit data
for NEW_PROJ_FILE in \
    "/Users/alex/Documents/Work/UWyo/Research/Flux Pipeline Project/Eddypro-ec-testing/workflows/basic_python/ini/pf_covariance_maximization.eddypro" \
    "/Users/alex/Documents/Work/UWyo/Research/Flux Pipeline Project/Eddypro-ec-testing/workflows/basic_python/ini/pf_covariance_maximization_with_default.eddypro" \
    "/Users/alex/Documents/Work/UWyo/Research/Flux Pipeline Project/Eddypro-ec-testing/workflows/basic_python/ini/pf_none.eddypro" 
do
    "${eddypro_rp}" \
        -s mac \
        -e "${environment}" \
        "${NEW_PROJ_FILE}"
    "${eddypro_fcc}" \
        -s mac \
        -e "${environment}" \
        "${NEW_PROJ_FILE}"
done
